# Generated by Django 6.0.7 on 2026-10-05 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_category_event_door_time_event_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline_prefix', models.CharField(default='Creating', max_length=255)),
                ('headline_highlight', models.CharField(default='Unforgettable', max_length=255)),
                ('headline_suffix', models.CharField(default='Experiences', max_length=255)),
                ('subtitle_prefix', models.CharField(default='with', max_length=255)),
                ('subtitle_brand', models.CharField(default='Kundwa', max_length=255)),
                ('glitch_words', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='Creating unforgettable experiences with world-class sound, lighting, and stage production.', null=True)),
                ('background_image', models.TextField(default='/14.jpg')),
                ('cta_buttons', models.JSONField(blank=True, default=list)),
                ('carousel_photos', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='services_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='tagline',
            field=models.TextField(blank=True, default='Creating unforgettable experiences with world-class sound, lighting, and stage production.', null=True),
        ),
    ]
